version: '2.3'
services:

  database:
    image: mysql:8.0.16
    container_name: database.dev
    command: mysqld --user=root --verbose
    restart: always
    ports:
      - "3306:3306"
    networks:
      default:
        aliases:
          - database
    environment:
      MYSQL_ROOT_PASSWORD: "U9e[FtrA^QC3Fv"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: "exit 0"

  registration:
    image: atmaram/webstore-registration:v0.0.1
    container_name: registration.service.dev
    ports:
      - "9001:80"
    networks:
      default:
        aliases:
          - registration
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: "database"
      DB_PORT: "3306"
      DB: "webstore-auth"
      DB_USER: "root"
      DB_PASSWORD: "U9e[FtrA^QC3Fv"
      SERVICE_PORT: 80
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://registration/registration/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  product:
    image: atmaram/webstore-product:v0.0.1
    container_name: product.service.dev
    networks:
      default:
        aliases:
          - product
    ports:
      - "9002:80"
    depends_on:
      database:
        condition: service_healthy
      registration:
        condition: service_healthy
    environment:
      DB_HOST: "database"
      DB_PORT: "3306"
      DB: "webstore-product"
      DB_USER: "root"
      DB_PASSWORD: "U9e[FtrA^QC3Fv"
      SERVICE_PORT: 80
      REGISTRATION_SERVICE: "http://registration/registration"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://product/product/health"]
      interval: 5s
      timeout: 5s
      retries: 10
  ui:
    image: atmaram/webstore-ui:v0.0.1
    container_name: webstore.ui.dev
    networks:
      default:
        aliases:
          - ui
    ports:
      - "9003:80"
    depends_on:
      registration:
        condition: service_healthy
      product:
        condition: service_healthy

  unifiedapi:
    image: atmaram/webstore-unifiedapi:v0.0.1
    container_name: unifiedapi.dev
    ports:
      - "80:80"
      - "9999:9999"
    environment:
      SERVICE_PORT: 80
      REGISTRATION: "registration:80"
      PRODUCT: "product:80"
      UI: "ui:80"
    networks:
      default:
        aliases:
          - unifiedapi
    depends_on:
      registration:
        condition: service_healthy
      product:
        condition: service_healthy
      ui:
        condition: service_started

networks:
  default:

